#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          phoenix
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Phoenix MailScanner
# Description:       Phoenix MailScanner
### END INIT INFO

# Author: Richard Lamboj <rl@uc-hq.com>

DESC="Phonix MailScanner"
DAEMON=/opt/phoenix/bin/phoenix

do_start()
{
    $DAEMON --daemon
}

do_stop()
{
    $DAEMON --stop
}

